name: sequitur_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
author: valauskasmodestas <valauskasmodestas@gmail.com>

environment:
  sdk: '>=2.0.0-dev.52.0 <3.0.0'

#dependencies:
#  path: ^1.4.1