name: sequitur_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
author: valauskasmodestas <valauskasmodestas@gmail.com>

environment:
  sdk: '>=2.12.0-29.7.beta <3.0.0'

dev_dependencies:
  extra_pedantic: ^1.2.0
